services:
  mongodb:
    image: "mongo"
    env_file:
      - ./env/mongo.env
    volumes:
      - mongodb:/data/db
  backend:
    build: ./
    env_file:
      - ./env/backend.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb:
